// window variables
export const WINDOW_RESIZED = "WINDOW_RESIZED";
// update tick
export const UPDATE_TICK = "UPDATE_TICK";
// authentiction
export const STORE_FINGERPRINT = "STORE_FINGERPRINT";
export const STORE_COOKIES = "STORE_COOKIES";
export const STORE_FORM_LOGIN = "STORE_FORM_LOGIN";
export const STORE_FORM_REGISTER = "STORE_FORM_REGISTER";
export const STORE_FORM_FORGOT = "STORE_FORM_FORGOT ";
export const SET_CONTEXT2D = "SET_CONTEXT2D";
export const SET_BACKGROUND_SOUND_CONTROLLER =
  "SET_BACKGROUND_SOUND_CONTROLLER";

const actionTypes = [
  SET_BACKGROUND_SOUND_CONTROLLER,
  WINDOW_RESIZED,
  UPDATE_TICK,
  STORE_FINGERPRINT,
  STORE_COOKIES,
  STORE_FORM_LOGIN,
  STORE_FORM_REGISTER,
  STORE_FORM_FORGOT,
  SET_CONTEXT2D,
];

export default actionTypes;
